# Generated by Django 5.0.6 on 2024-05-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='contactNo',
            field=models.CharField(max_length=10),
        ),
    ]
