# Generated by Django 5.0.6 on 2024-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0002_alter_realestate_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='contactNo',
        ),
        migrations.AddField(
            model_name='realestate',
            name='contactno',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
