# Generated by Django 5.0.6 on 2024-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0003_remove_realestate_contactno_realestate_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='contactno',
        ),
        migrations.AddField(
            model_name='realestate',
            name='contactNo',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
