# Generated by Django 5.0.6 on 2024-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0005_rename_confirmpassword_realestate_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='contact_no',
            field=models.IntegerField(default='20', max_length=20),
        ),
    ]
