# Generated by Django 5.0.6 on 2024-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0006_alter_realestate_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Fathername', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelTable(
            name='realestate',
            table=None,
        ),
    ]
