# Generated by Django 5.0.6 on 2024-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0007_clientregistration_alter_realestate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='contact_no',
            field=models.PositiveBigIntegerField(default='500', max_length=500),
        ),
    ]
