# Generated by Django 5.0.6 on 2024-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0009_details_delete_clientregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('contact_no', models.PositiveBigIntegerField()),
                ('area_name', models.CharField(max_length=20)),
                ('booked_amount', models.PositiveBigIntegerField()),
                ('reg_amt', models.PositiveBigIntegerField()),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='client_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('plot_seen', models.PositiveBigIntegerField()),
                ('amount_Details', models.PositiveBigIntegerField()),
                ('requirements', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='plotinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('No_of_plots', models.PositiveBigIntegerField()),
                ('square_feet', models.PositiveBigIntegerField()),
                ('square_feet_rate', models.PositiveBigIntegerField()),
                ('Amenities', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='plotsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('No_of_plots', models.PositiveBigIntegerField()),
                ('square_feet', models.PositiveBigIntegerField()),
                ('amenities', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('address', models.CharField(default=0, max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
    ]
