# Generated by Django 5.0.6 on 2024-06-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0011_remove_plotinfo_square_feet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotsdetails',
            old_name='square_feet',
            new_name='square_feet_rate',
        ),
    ]
