# Generated by Django 5.0.6 on 2024-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0012_rename_square_feet_plotsdetails_square_feet_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_req',
            name='requirements',
            field=models.CharField(max_length=200),
        ),
    ]
