# Generated by Django 5.0.6 on 2024-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0013_alter_client_req_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotinfo',
            name='Amenities',
            field=models.CharField(max_length=200),
        ),
    ]
