# Generated by Django 5.0.6 on 2024-06-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatedetails', '0015_alter_plotsdetails_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
